#!/bin/bash

# █▀▀ █▀▀ ▀█▀ █▀▀ █░█    █░█ █▀█ █▀▀ █▀█ █▀▄▀█ █ █▄░█ █▀▀ 
# █▀░ ██▄ ░█░ █▄▄ █▀█    █▄█ █▀▀ █▄▄ █▄█ █░▀░█ █ █░▀█ █▄█ 

# tiny helper script to parse cal cache file for upcoming events because
# escaping the double quotes was a bitch
# the cal cache file contains events from 5 month ago to 5 months from now

cachefile=$1
date=$2

awk -F, ' BEGIN { "echo '$date'" | getline a } { if ( $0>a ) { print $0 }} ' $cachefile | head -30
