#!/bin/bash

# █░█░█ █▀▀ ▄▀█ ▀█▀ █░█ █▀▀ █▀█    █▀▀ █▀█ █▀█ █▀▀ █▀▀ ▄▀█ █▀ ▀█▀ 
# ▀▄▀▄▀ ██▄ █▀█ ░█░ █▀█ ██▄ █▀▄    █▀░ █▄█ █▀▄ ██▄ █▄▄ █▀█ ▄█ ░█░ 

UNITS=$1
LAT=$2
LON=$3
API_KEY=$4

CACHE_PATH="$HOME/.cache/awesome/weather-forecast"

curl "https://api.openweathermap.org/data/2.5/forecast?units=$UNITS&lat=$LAT&lon=$LON&appid=$API_KEY&cnt=4" | tee $CACHE_PATH
