#!/bin/bash

# █ █▀▄ █▀▀ ▄▀█ █▀█ ▄▀█ █▀▄    █▀▀ █▀▄▀█    ▀█▀ █▀█ █▀▀ █▀▀ █░░ █▀▀ 
# █ █▄▀ ██▄ █▀█ █▀▀ █▀█ █▄▀    █▄▄ █░▀░█    ░█░ █▄█ █▄█ █▄█ █▄▄ ██▄ 

# Toggles conservation mode on Lenovo laptops
# The script requires root privileges; add it to /etc/sudoers

status=$(ideapad-cm status)

if [[ $status == *"enabled"* ]]; then
  ideapad-cm disable
  echo "Disabling conservation mode"
else
  ideapad-cm enable
  echo "Enabling conservation mode"
fi
