#!/bin/bash

# Outputs a random title from a list of titles

titles=(
  "Mechromancer"
  "Linux enthusiast"
  "Uses Arch, btw"
  "Terminal dweller"
)

rand=$[$RANDOM % ${#titles[@]}]
echo ${titles[$rand]}

